-- MySQL Script generated by MySQL Workbench
-- Thu Jan 18 15:11:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema habit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema habit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `habit` DEFAULT CHARACTER SET utf8 ;
USE `habit` ;

-- -----------------------------------------------------
-- Table `habit`.`h_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit`.`h_user` (
  `i_id` INT NOT NULL,
  `v_wechatuid` VARCHAR(45) NULL COMMENT '微信用户唯一标识',
  `v_name` VARCHAR(45) NULL COMMENT '用户名称',
  `ti_sex` TINYINT NOT NULL DEFAULT 0 COMMENT '性别，0男，1女',
  `d_birthday` DATE NULL COMMENT '用户生日',
  `v_tel` VARCHAR(20) NULL COMMENT '用户电话',
  `dt_cdate` DATETIME NULL,
  `v_imgurl` VARCHAR(45) NULL COMMENT '用户头像链接',
  PRIMARY KEY (`i_id`),
  UNIQUE INDEX `wechat_user_id_UNIQUE` (`v_wechatuid` ASC),
  UNIQUE INDEX `birthday_UNIQUE` (`d_birthday` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habit`.`h_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit`.`h_action` (
  `i_id` INT NOT NULL,
  `v_name` VARCHAR(45) NULL COMMENT '动作名称',
  `ti_type` TINYINT NULL COMMENT '动作类型，0计次动作，1计时动作',
  `v_unit` VARCHAR(45) NULL COMMENT '如果是计次动作，则该字段标识计次的单位',
  `i_userid` INT NULL DEFAULT NULL COMMENT '用户id外键',
  `s_state` TINYINT NOT NULL COMMENT '状态，0未删除，1已删除，默认0',
  `dt_cdate` DATETIME NULL,
  PRIMARY KEY (`i_id`),
  INDEX `user_id_idx` (`i_userid` ASC),
  CONSTRAINT `h_action_user_id`
    FOREIGN KEY (`i_userid`)
    REFERENCES `habit`.`h_user` (`i_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habit`.`h_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit`.`h_plan` (
  `i_id` INT NOT NULL,
  `v_name` VARCHAR(45) NULL COMMENT '训练名称',
  `dt_cdate` DATETIME NULL COMMENT '记录创建时间',
  `ti_state` TINYINT NULL COMMENT '0未删除，1已删除',
  `i_userid` INT NULL,
  PRIMARY KEY (`i_id`),
  INDEX `user_id_idx` (`i_userid` ASC),
  CONSTRAINT `h_plan_user_id`
    FOREIGN KEY (`i_userid`)
    REFERENCES `habit`.`h_user` (`i_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habit`.`h_body_data_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit`.`h_body_data_log` (
  `i_id` INT NOT NULL,
  `i_userid` INT NULL,
  `ti_index` TINYINT NULL COMMENT '关联的指标，0身高，1体重，2体脂，3肩围，4胸围，5腰围，6腹围，7臀围，8左大臂围，9右大臂围，10左小臂围，11右小臂围，12左大腿围，13右大腿围，14左小腿围，15右小腿围',
  `f_score` FLOAT NULL COMMENT '成绩',
  `dt_cdate` DATETIME NULL COMMENT '创建时间',
  `v_comments` VARCHAR(45) NULL COMMENT '感悟',
  PRIMARY KEY (`i_id`),
  INDEX `user_id_idx` (`i_userid` ASC),
  CONSTRAINT `h_body_data_log_user_id`
    FOREIGN KEY (`i_userid`)
    REFERENCES `habit`.`h_user` (`i_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habit`.`h_target`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit`.`h_target` (
  `i_id` INT NOT NULL,
  `i_userid` INT NULL,
  `ti_index` TINYINT NULL COMMENT '关联的指标，0身高，1体重，2体脂，3肩围，4胸围，5腰围，6腹围，7臀围，8左大臂围，9右大臂围，10左小臂围，11右小臂围，12左大腿围，13右大腿围，14左小腿围，15右小腿围',
  `ti_nexus` TINYINT NULL COMMENT '关系，0大于等于目标值，1小于等于目标',
  `f_value` FLOAT NULL COMMENT '目标值',
  `ti_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '指标状态，如果达到关联关系的目标值，则目标完成，否则未完成\n0未完成，1已完成',
  `ti_state` TINYINT NOT NULL DEFAULT 0 COMMENT '状态，0未删除，1已删除，默认0',
  `dt_cdate` DATETIME NULL,
  INDEX `user_id_idx` (`i_userid` ASC),
  PRIMARY KEY (`i_id`),
  CONSTRAINT `h_target_user_id`
    FOREIGN KEY (`i_userid`)
    REFERENCES `habit`.`h_user` (`i_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habit`.`h_body_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit`.`h_body_data` (
  `i_id` INT NOT NULL,
  `i_userid` INT NULL COMMENT '用户id外键',
  `f_lastheight` FLOAT NULL COMMENT '最后一次身高',
  `f_lastweight` FLOAT NULL COMMENT '最后一次体重',
  `f_lastbodyfat` FLOAT NULL COMMENT '最后一次体脂率',
  `f_lastshouldersize` FLOAT NULL COMMENT '最后一次肩宽',
  `f_lastbust` FLOAT NULL COMMENT '最后一次胸围',
  `f_lastabdominalsize` FLOAT NULL COMMENT '最后一次腹围',
  `f_lastwaistline` FLOAT NULL COMMENT '最后一次腰围',
  `f_lasthipline` FLOAT NULL COMMENT '最后一次臀围',
  `f_lastlforearmsize` FLOAT NULL COMMENT '最后一次左小臂围',
  `f_lastrforearmsize` FLOAT NULL COMMENT '最后一次右小臂围',
  `f_lastlarmsize` FLOAT NULL COMMENT '最后一次左大臂围',
  `f_lastrarmsize` FLOAT NULL COMMENT '最后一次右大臂围',
  `f_lastlthighsize` FLOAT NULL COMMENT '最后一次左大腿围',
  `f_lastrthighsize` FLOAT NULL COMMENT '最后一次右大腿围',
  `f_lastlcrussize` FLOAT NULL COMMENT '最后一次左小腿围',
  `f_lastrcrussize` FLOAT NULL COMMENT '最后一次右小腿围',
  INDEX `user_id_idx` (`i_userid` ASC),
  CONSTRAINT `h_body_data_user_id`
    FOREIGN KEY (`i_userid`)
    REFERENCES `habit`.`h_user` (`i_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habit`.`h_plan_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit`.`h_plan_action` (
  `i_planid` INT NULL,
  `i_actionid` INT NULL,
  `i_num` INT NULL COMMENT '本动作的组数',
  `dt_cdate` DATETIME NULL COMMENT '创建时间',
  `ti_state` TINYINT NULL COMMENT '0未删除，1已删除',
  INDEX `plan_id_idx` (`i_planid` ASC),
  INDEX `action_id_idx` (`i_actionid` ASC),
  CONSTRAINT `plan_action_plan_id`
    FOREIGN KEY (`i_planid`)
    REFERENCES `habit`.`h_plan` (`i_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `plan_action_action_id`
    FOREIGN KEY (`i_actionid`)
    REFERENCES `habit`.`h_action` (`i_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habit`.`h_plan_action_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit`.`h_plan_action_log` (
  `i_id` INT NOT NULL,
  `i_planlogid` INT NULL COMMENT '本次训练的训练日志，同次训练的plan_log_id相同',
  `i_planid` INT NULL COMMENT '训练的id',
  `i_actionid` INT NULL COMMENT '动作的id',
  `v_planname` VARCHAR(45) NULL COMMENT '所属训练的名称',
  `v_actionname` VARCHAR(45) NULL COMMENT '所属动作的名称',
  `ti_actiontype` TINYINT NULL COMMENT '所属动作的类型，0记次动作，1计时动作',
  `v_actionunit` VARCHAR(45) NULL COMMENT '如果是记次动作，则表示记次单位',
  `i_numbyplan` INT NULL COMMENT '本次训练的第几组',
  `f_scoreweight` FLOAT NULL COMMENT '本组训练的负重',
  `i_scorenum` INT NULL COMMENT '本组动作的完成次数',
  `v_comments` VARCHAR(45) NULL COMMENT '感悟备注',
  `i_scoretime` INT NULL COMMENT '本组训练的持续时间',
  `dt_cdate` DATETIME NULL COMMENT '创建时间\n',
  `dt_ledate` DATETIME NULL COMMENT '最后修改时间',
  `ti_state` TINYINT NULL COMMENT '状态，0训练中，1训练完成',
  PRIMARY KEY (`i_id`),
  INDEX `plan_id_idx` (`i_planid` ASC),
  INDEX `action_id_idx` (`i_actionid` ASC),
  CONSTRAINT `h_plan_action_log_plan_id`
    FOREIGN KEY (`i_planid`)
    REFERENCES `habit`.`h_plan` (`i_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `h_plan_action_log_action_id`
    FOREIGN KEY (`i_actionid`)
    REFERENCES `habit`.`h_action` (`i_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
